import { Inter } from "next/font/google";
import "./globals.css";
import CCIcon from "./components/CCIcon";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className+ " bg-gradient-to-b from-blue-500 to-purple-300 min-h-screen"}>
        <main className="p-4 max-w-2xl mx-auto">
        <header className="flex justify-between my-8 items-center">
        <a href ="" className="inline-flex gap-1 items-center">
        <CCIcon/>
         <span>Captioner</span> 
          </a>
        <nav className="flex gap-6 text-black/80">
          <a href="">Home</a>
          <a href="">Pricing</a>
          <a href="">Contact</a>
        </nav>
      </header>
      {children}
        </main>
      </body>
    
    </html>
  );
}
